### ISSUE TITLE
mac打包报错

### ISSUE THREAD

**Issue by phpk** [foldl/chatllm.cpp#11]
109 warnings and 1 error generated.
make[2]: *** [CMakeFiles/main.dir/models.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 warning generated.
1 warning generated.
make[1]: *** [CMakeFiles/main.dir/all] Error 2
make: *** [all] Error 2

mac version: ventura 13.6.6

**Comment by phpk** [comment]
chatllm.cpp/models/llama.cpp:50:152: error: no matching constructor for initialization of 'Config'
                                    Model<BaseConfig, Embedding, RMSNorm, LayerBlock, int, int, int, int, int>>(type, config, MEM_SIZE, SCRATCH_SIZE), config(config)
chatllm.cpp/models/llama.cpp:3:12: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'const BaseConfig' to 'const chatllm::llama::v2::Config' for 1st argument
    struct Config : public BaseConfig

chatllm.cpp/models/llama.cpp:3:12: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 1 was provided

**Comment by foldl** [comment]
Which compiler are you using? and which version?

**Comment by foldl** [comment]
You can update and have a try. I think it can be fixed by 23d76fbab2678b99da2cd8eea1508481288f09c1.

**Comment by phpk** [comment]
Compiled successfully, thanks！
