### ISSUE TITLE
Compilation of bindings under macOS does not succeed

### ISSUE THREAD

**Issue by phpk** [foldl/chatllm.cpp#12]
cmake --build build --target libchatllm
error！

suggest：

bindings/libchatllm.h 
the 7 line add this

#elif defined(__APPLE__) && defined(__MACH__) // macOS or iOS
    #define API_CALL
    #if (!defined __x86_64__) && (!defined __arm64__)
        #error unsupported target architecture
    #endif

**Comment by foldl** [comment]
Thanks for your reporting and suggestion.

Fixed in: https://github.com/foldl/chatllm.cpp/commit/b184a69d00b937e8ef5817965470710ecdebaa78
