### ISSUE TITLE
The same sentence appears in loop

### ISSUE THREAD

**Issue by ChenHuge** [foldl/chatllm.cpp#19]
Hi,  Foldl.
I am learning about your program.
After testing, I found that it will start to appear the same sentence after a few answers and keep looping. But this problem does not occur on llama.cpp.
I can provide the testing ENV and how can I contact you.
Thanks you.

![image](https://github.com/foldl/chatllm.cpp/assets/14805139/ff38e5e8-c874-4a7a-8e95-0aa4f632c997)

**Comment by foldl** [comment]
Which model?

**Comment by ChenHuge** [comment]
I've tested qwen, gemma, and llama, all models have this issue, but it doesn't happen every time.

**Comment by foldl** [comment]
chatllm.cpp does not have repetition penalty yet. You can try `greedy` or `tfs` sampling by `--temp 0` or `--sampling tfs`.
