### ISSUE TITLE
RuntimeError: Internal: could not parse ModelProto from /home/james/glm-4-9b-chat/tokenizer.model

### ISSUE THREAD

**Issue by jamfor999** [foldl/chatllm.cpp#20]
After checking out:

`git clone https://huggingface.co/THUDM/glm-4-9b-chat ~/glm4`

Then running from this repo:

`python3 convert.py -i ~/glm-4-9b-chat/ -t q8_0 -o quantized.bin`

The following occurs:

```
Loading vocab file /home/james/glm-4-9b-chat/tokenizer.model
Traceback (most recent call last):
  File "/home/james/chatllm.cpp/convert.py", line 3553, in <module>
    main()
  File "/home/james/chatllm.cpp/convert.py", line 3301, in main
    vocab = load_vocab(vocab_dir, skip_def_vocab_model)
  File "/home/james/chatllm.cpp/convert.py", line 3204, in load_vocab
    return load_spm(path2)
  File "/home/james/chatllm.cpp/convert.py", line 3192, in load_spm
    return SentencePieceVocab(p, added_tokens_path if added_tokens_path.exists() else None)
  File "/home/james/chatllm.cpp/convert.py", line 355, in __init__
    self.sentencepiece_tokenizer = SentencePieceProcessor(str(fname_tokenizer))
  File "/home/james/.venv3.9/lib64/python3.9/site-packages/sentencepiece/__init__.py", line 468, in Init
    self.Load(model_file=model_file, model_proto=model_proto)
  File "/home/james/.venv3.9/lib64/python3.9/site-packages/sentencepiece/__init__.py", line 961, in Load
    return self.LoadFromFile(model_file)
  File "/home/james/.venv3.9/lib64/python3.9/site-packages/sentencepiece/__init__.py", line 316, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: could not parse ModelProto from /home/james/glm-4-9b-chat/tokenizer.model
```

Tried this with various python versions, and nothing seems to work.

**Comment by matteoserva** [comment]
Apparently there is a naming issue with the glm model. I fixed it by manually forcing the model type inside convert.py.
Here is a patch that can fix the conversion:
`
diff --git a/convert.py b/convert.py
index 12907b7..3b31e89 100644
--- a/convert.py
+++ b/convert.py
@@ -3295,7 +3295,8 @@ def main():
 
     vocab_dir = Path(args.model_name_or_path) if args.vocab_dir == '' else Path(args.vocab_dir)
 
-    if config._name_or_path == 'THUDM/glm-4-9b-chat':
+    print(config._name_or_path)
+    if config._name_or_path == 'THUDM/glm4-9b-chat':
         vocab = load_vocab_from_tiktok_mergeable_ranks(vocab_dir / 'tokenizer.model')
     else:
         vocab = load_vocab(vocab_dir, skip_def_vocab_model)
@@ -3315,7 +3316,7 @@ def main():
     #    model = PeftModel.from_pretrained(model, args.lora_model_name_or_path)
     #    model = model.merge_and_unload()
 
-    if arch == 'ChatGLMModel':
+    if arch == 'ChatGLMModel' or True:
         if hasattr(config, "multi_query_attention"):
             if config.rope_ratio is not None:
                 ChatGLM4Converter.convert(config, model_files, vocab, ggml_type, args.save_path)
`

**Comment by foldl** [comment]
Fixed.
