### ISSUE TITLE
crashed using qwen2  72b

### ISSUE THREAD

**Issue by cagev** [foldl/chatllm.cpp#21]
./bin/main -m ~/aimodels/chatmodels/qwen2-72bi_q8_0.bin -i 
    ________          __  __    __    __  ___ (通义千问)
   / ____/ /_  ____ _/ /_/ /   / /   /  |/  /_________  ____  
  / /   / __ \/ __ `/ __/ /   / /   / /|_/ // ___/ __ \/ __ \ 
 / /___/ / / / /_/ / /_/ /___/ /___/ /  / // /__/ /_/ / /_/ / 
 \____/_/ /_/\__,_/\__/_____/_____/_/  /_(_)___/ .___/ .___/  
You are served by QWen2,                      /_/   /_/       
with 72706203648 (72.7B) parameters.

You  > hi
A.I. > GGML_ASSERT: /home/arthur/work/chatllm.cpp/ggml/src/ggml.c:17428: cgraph->n_nodes < cgraph->size
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
No stack.
The program is not being run.

qwen2-72bi_q8_0.bin is quantized  from qwen2-Instruct-72B   [Instruct-72B](https://huggingface.co/Qwen/Qwen2-72B-Instruct)

**Comment by foldl** [comment]
Thanks for reporting. I think c6c76da6a022d9e5606417fd5a66ebb8fec89b36 can fix this.

By the way, I have not tested 72B due to limited compute resources.

**Comment by cagev** [comment]
It works, thanks for your great job.  I test on my pc with cpu 5900x and 64G ram,  it works, buf very slow. 

```shell 
./bin/main -m ~/aimodels/chatmodels/qwen2-72bi_q8_0.bin -i 
    ________          __  __    __    __  ___ (通义千问)
   / ____/ /_  ____ _/ /_/ /   / /   /  |/  /_________  ____  
  / /   / __ \/ __ `/ __/ /   / /   / /|_/ // ___/ __ \/ __ \ 
 / /___/ / / / /_/ / /_/ /___/ /___/ /  / // /__/ /_/ / /_/ / 
 \____/_/ /_/\__,_/\__/_____/_____/_/  /_(_)___/ .___/ .___/  
You are served by QWen2,                      /_/   /_/       
with 72706203648 (72.7B) parameters.

You  > hi
A.I. > Hello! How can I assist you today?
You  > 

```
