### ISSUE TITLE
bindings里面的openai_api.ts好像读不到历史信息

### ISSUE THREAD

**Issue by gabrielpondc** [foldl/chatllm.cpp#22]
只能读取到最新一条，好像对system以及之前的历史信息都没有反应

用python的openai_api.py报错如下

```shell
.../chatllm.cpp/bindings -> python openai_api.py -i -m /2T/Langchain-Ch/Langchain-Chatchat/THUDM/glm-4-9b-chat-1m/glm-4-9b-chat-1m/chatllm.cpp/models/chatglm-ggml.bin
Traceback (most recent call last):
  File "/2T/Langchain-Ch/Langchain-Chatchat/THUDM/glm-4-9b-chat-1m/glm-4-9b-chat-1m/chatllm.cpp/bindings/openai_api.py", line 280, in <module>
    chat_streamer = ChatLLMStreamer(ChatLLM(LibChatLLM(), basic_args + [args[0]] + chat_args, False))
  File "/2T/Langchain-Ch/Langchain-Chatchat/THUDM/glm-4-9b-chat-1m/glm-4-9b-chat-1m/chatllm.cpp/bindings/chatllm.py", line 216, in __init__
    self.llm.start()
  File "/2T/Langchain-Ch/Langchain-Chatchat/THUDM/glm-4-9b-chat-1m/glm-4-9b-chat-1m/chatllm.cpp/bindings/chatllm.py", line 161, in start
    raise Exception(f'ChatLLM: failed to `start()` with error code {r}')
Exception: ChatLLM: failed to `start()` with error code 4
```

**Comment by foldl** [comment]
`openai_api.ts` 有问题（bun 有 bug）。使用 `openai_api.py` 时，传的参数有误，请参考：

> `openai_api.py` takes two arguments specifying models for chatting and code completion respectively. For example, use
> DeepSeekCoder instructed for chatting, and its base model for code completion:
>
> ```sh
> python openai_api.py path/to/deepseekcoder-1.3b.bin /path/to/deepseekcoder-1.3b-base.bin
> ```
> 
> Additional arguments for each model can be specified too. For example:
> 
> ```sh
> python openai_api.py path/to/chat/model /path/to/fim/model --temp 0 --top_k 2 --- --temp 0.8
> ```

**Comment by gabrielpondc** [comment]
好的，了解，另外在转glm4的base的模型的时候，使用`convert.py`有报错，发现是glm4base的模型参数中并没有`rope_ratio`,所以模型走到了`ChatGLMConverter.convert(config, model_files, vocab, ggml_type, args.save_path)`这一条，但是glm4的参数中有列表并不是integer，类型不符合`f.write(struct.pack("i" * len(config_values), *config_values))`这一步时候出错。修改过`if config.rope_ratio is not None or ('glm-4' in config._name_or_path)`后走到`ChatGLM4Converter.convert(config, model_files, vocab, ggml_type, args.save_path)`但是同样因为模型参数没有`rope_ratio`因此报错，目前是将rope_ratio先临时加到了base模型参数中，暂不知对模型是否有影响。

**Comment by gabrielpondc** [comment]
使用上述方法转的模型加载进python的`openai_api.py`也没有报错，也没有成功的样式，后台正常挂载，发送请求一直转圈，但是CPU也没有被使用的迹象。
![image](https://github.com/foldl/chatllm.cpp/assets/26787778/00229af5-cb90-4855-bc44-b89248570752)

**Comment by gabrielpondc** [comment]
目前测试暂无影响，但是好像推理速度很慢～
