### ISSUE TITLE
gemma模型的bug

### ISSUE THREAD

**Issue by phpk** [foldl/chatllm.cpp#26]
% ./main -m gemma-1.1-2b.bin -i
    ________          __  __    __    __  ___ 
   / ____/ /_  ____ _/ /_/ /   / /   /  |/  /_________  ____  
  / /   / __ \/ __ `/ __/ /   / /   / /|_/ // ___/ __ \/ __ \ 
 / /___/ / / / /_/ / /_/ /___/ /___/ /  / // /__/ /_/ / /_/ / 
 \____/_/ /_/\__,_/\__/_____/_____/_/  /_(_)___/ .___/ .___/  
You are served by Gemma,                      /_/   /_/       
with 2506172416 (2.5B) parameters.

You  > 你好，你叫什么名字
A.I. > 我的名字是 AI，我是一个语言模型，没有个人名称。我致力于提供您有用的信息和帮助。请随时提出任何问题或要求。我期待您的问题！我是一个语言模型，没有个人名称。但是，我可以提供您有用的信息和帮助。请随时提出任何问题或要求。我期待您的问题！我是一个语言模型，没有个人名称。但是，我可以提供您有用的信息和帮助。请随时提出任何问题或要求。我期待您的问题！我是一个语言模型，没有个人名称。但是，我可以提供您有用的信息和帮助。请随时提出任何问题或要求。我期待您的问题！我是一个语言模型，没有个人名称。但是，我可以提供您有用的信息和帮助。请随时提出任何问题或要求。我期待您的问题！我是一个语言模型，没有个人名称。但是，我可以提供您有用的信息和帮助。请随时提出任何问题或要求。我期待您的问题！我是一个语言模型，没有个人名称。但是，我可以提供您有用的信息和帮助。请随时提出任何问题或要

会不停止，一直回复下去

**Comment by phpk** [comment]
./main -m minicpm-dpo-q4_1.bin 
 你好！很高兴能帮助你。有什么问题或需要我帮忙的吗？我会尽力提供有用的信息和帮助。

timings: prompt eval time =     83648.52 ms /     9 tokens (  9294.28 ms per token,     0.11 tokens per second)
timings:        eval time =    168268.54 ms /    21 tokens (  8012.79 ms per token,     0.12 tokens per second)
timings:       total time =    251917.06 ms /    30 tokens 另外一个模型，直接跳出对话，而且加载很久

**Comment by foldl** [comment]
Repeat penalty is not implemented yet. Current methods (such as frequency penalty) do not make much sense to me. See also #19.

Regarding the performance on MiniCPM, is it built in debug mode?

Without `-i`, the program terminates after an answer is generated for the `-p` prompt.

**Comment by phpk** [comment]
thinks!
