### ISSUE TITLE
提供python调用方式

### ISSUE THREAD

**Issue by wzg-zhuo** [foldl/chatllm.cpp#3]
参考chatglm.cpp，能否支持python推理

**Comment by wzg-zhuo** [comment]
能否提供chatllm_pybind.cpp,_C.py,__init__.py等文件，谢谢

**Comment by foldl** [comment]
I will do it after later. Stay tuned.

**Comment by wzg-zhuo** [comment]
ok thx

**Comment by foldl** [comment]
Here we go: https://github.com/foldl/chatllm.cpp/blob/master/docs/binding.md

**Comment by foldl** [comment]
Here a Chatbot web demo:

https://github.com/foldl/chatllm.cpp/blob/master/bindings/chatllm_st.py
