### ISSUE TITLE
phi 3.5 moe usage

### ISSUE THREAD

**Issue by GlasslessPizza** [foldl/chatllm.cpp#31]
The `model_downloader.py` script doesn't list the recently supported phi 3.5 moe.
I'd like to also know if it's ok to use the v0.3 release from Jul 6 as-is to run it.
Thanks!

**Comment by ayttop** [comment]
microsoft/Phi-3.5-MoE-instruct/??????????????????????????

**Comment by ayttop** [comment]
how to convert microsoft/Phi-3.5-MoE-instruct to gguf?

**Comment by foldl** [comment]
@GlasslessPizza You can try the latest v0.4 or build it yourself.

You can use `-m :phi3.5:moe` in Python binding.

**Comment by foldl** [comment]
@ayttop Sorry, GGUF is not supported. This project uses something like the old GGML file format.

**Comment by ayttop** [comment]
Can the form be converted to ggml     and any body convert it to gguf>?

**Comment by foldl** [comment]
No.
