### ISSUE TITLE
Question:Can we use chatllm.cpp in Android System

### ISSUE THREAD

**Issue by FranzKafkaYu** [foldl/chatllm.cpp#36]
Hello developer,I  want to know whether your project can be used in android system?I am looking a better method for inference in embeded devices like Android etc.  

currently I am using llama.cpp and its performance is decent,with Qualcomm Snapdragon Gen2 I can get 20 tokens/s,with MTK dimensity 9300 I can get 35 tokens/s,do you test in any embeded devices?

**Comment by foldl** [comment]
Yes, you can.

This project is also based on ggml just like llama.cpp. This project can't be a _better_ (aka faster) method when llama.cpp is already there.
