### ISSUE TITLE
Thanks for great llm-inference engine. I made Nim bindings for it with help of Llama 405b.

### ISSUE THREAD

**Issue by JohnClaw** [foldl/chatllm.cpp#40]
Hi. I used Llama 405b (https://cloud.sambanova.ai/) to make Nim bindings for chatllm.cpp. So llama 405b generated two files: main.nim and libchatllm.nim. To compile main.exe you should install nim from official site (https://nim-lang.org/install_windows.html). After installing Nim you should put main.nim, libchatllm.nim, libchatllm.dll and ggml.dll into the folder where your nim.exe is (C:\Nim\bin, for example). Then create .bat file with following command inside of it: ```nim.exe -d:release c main.nim``` and execute this bat. Main.nim and libchatllm.nim can be found in attached .zip archive.
[Nim_bindings_for_chatllm.cpp.zip](https://github.com/user-attachments/files/17793174/Nim_bindings_for_chatllm.cpp.zip)

**Comment by JohnClaw** [comment]
Main.nim `import system
import strutils
import os
import libchatllm

proc chatllm_print(user_data: pointer, print_type: PrintType, utf8_str: cstring) {.cdecl.} =
  case print_type
  of PRINT_CHAT_CHUNK:
    stdout.write(utf8_str)
  else:
    echo utf8_str
  stdout.flushFile()

proc chatllm_end(user_data: pointer) {.cdecl.} =
  echo ""

proc main() =
  let chat = chatllm_create()
  for i in 1 .. paramCount():
    chatllm_append_param(chat, paramStr(i).cstring)

  let r = chatllm_start(chat, chatllm_print, chatllm_end, nil)
  if r != 0:
    echo ">>> chatllm_start error: ", r
    quit(r)

  while true:
    stdout.write("You  > ")
    let input = stdin.readLine()
    if input.isEmptyOrWhitespace(): continue

    stdout.write("A.I. > ")
    let r = chatllm_user_input(chat, input.cstring)
    if r != 0:
      echo ">>> chatllm_user_input error: ", r
      break

main()
`

**Comment by JohnClaw** [comment]
```
type
  PrintType* = enum
    PRINT_CHAT_CHUNK = 0,
    PRINTLN_META = 1,
    PRINTLN_ERROR = 2,
    PRINTLN_REF = 3,
    PRINTLN_REWRITTEN_QUERY = 4,
    PRINTLN_HISTORY_USER = 5,
    PRINTLN_HISTORY_AI = 6,
    PRINTLN_TOOL_CALLING = 7,
    PRINTLN_EMBEDDING = 8,
    PRINTLN_RANKING = 9,
    PRINTLN_TOKEN_IDS = 10

  ChatllmObj* = object

  ChatllmPrintProc* = proc (user_data: pointer, print_type: PrintType, utf8_str: cstring) {.cdecl.}
  ChatllmEndProc* = proc (user_data: pointer) {.cdecl.}

const
  libName = "libchatllm.dll"

proc chatllm_create*(): ptr ChatllmObj {.cdecl, dynlib: libName, importc.}

proc chatllm_append_param*(obj: ptr ChatllmObj, utf8_str: cstring) {.cdecl, dynlib: libName, importc.}

proc chatllm_start*(obj: ptr ChatllmObj, f_print: ChatllmPrintProc, f_end: ChatllmEndProc, user_data: pointer): cint {.cdecl, dynlib: libName, importc.}

proc chatllm_set_gen_max_tokens*(obj: ptr ChatllmObj, gen_max_tokens: cint) {.cdecl, dynlib: libName, importc.}

proc chatllm_restart*(obj: ptr ChatllmObj, utf8_sys_prompt: cstring) {.cdecl, dynlib: libName, importc.}

proc chatllm_user_input*(obj: ptr ChatllmObj, utf8_str: cstring): cint {.cdecl, dynlib: libName, importc.}

proc chatllm_set_ai_prefix*(obj: ptr ChatllmObj, utf8_str: cstring): cint {.cdecl, dynlib: libName, importc.}

proc chatllm_tool_input*(obj: ptr ChatllmObj, utf8_str: cstring): cint {.cdecl, dynlib: libName, importc.}

proc chatllm_tool_completion*(obj: ptr ChatllmObj, utf8_str: cstring): cint {.cdecl, dynlib: libName, importc.}

proc chatllm_text_tokenize*(obj: ptr ChatllmObj, utf8_str: cstring): cint {.cdecl, dynlib: libName, importc.}

proc chatllm_text_embedding*(obj: ptr ChatllmObj, utf8_str: cstring): cint {.cdecl, dynlib: libName, importc.}

proc chatllm_qa_rank*(obj: ptr ChatllmObj, utf8_str_q: cstring, utf8_str_a: cstring): cint {.cdecl, dynlib: libName, importc.}

proc chatllm_rag_select_store*(obj: ptr ChatllmObj, name: cstring): cint {.cdecl, dynlib: libName, importc.}

proc chatllm_abort_generation*(obj: ptr ChatllmObj) {.cdecl, dynlib: libName, importc.}

proc chatllm_show_statistics*(obj: ptr ChatllmObj) {.cdecl, dynlib: libName, importc.}

proc chatllm_save_session*(obj: ptr ChatllmObj, utf8_str: cstring): cint {.cdecl, dynlib: libName, importc.}

proc chatllm_load_session*(obj: ptr ChatllmObj, utf8_str: cstring): cint {.cdecl, dynlib: libName, importc.}

```

**Comment by JohnClaw** [comment]
> Nice. Could you make a PR for this?

I'm sorry i'm not a tech guy and English is not my native language. Due to these facts github interface isn't user-friendly for me. I don't know how to open PR.

**Comment by JohnClaw** [comment]
> A question: could you use this inference engine and another smaller model to generate the Nim code? Then, it seems that we are bootstrapping

Small models are to weak for coding tasks. Even Qwen 2.5 Coder Instruct 32b failed my request to create properly working Nim bindings for chatllm.cpp. Only giant Llama 405b solved the problem correctly.

**Comment by JohnClaw** [comment]
> A question: could you use this inference engine and another smaller model to generate the Nim code? Then, it seems that we are bootstrapping

But as soon as you asked, i promted Nim-compiled main.exe to generate Nim code for console snake game using gemma 2 2b. 

```
You are served by Gemma-2,                   
with 2614341888 (2.6B) parameters.

You  > Write Nim code for console snake game.
A.I. > ```nim
import std

proc main() =
    # Initialize game variables
    var snake = [ (0, 0) ]
    var food = (0, 0)
    var direction = "right"
    var length = 1
    var score = 0

    # Set up the console window
    print("Welcome to the Snake Game!")

    # Game loop
    while true =
        # Get user input
        var input = readLine()

        # Handle user input
        if input == "w" and direction != "down" then
            direction = "up"
        elif input == "s" and direction != "up" then
            direction = "down"
        elif input == "a" and direction != "right" then
            direction = "left"
        elif input == "d" and direction != "left" then
            direction = "right"

        # Move the snake
        snake = snake[1]

        # Check for collisions
        if snake[0] == food[0] and snake[1] == food[1] then
            length += 1
            food = (random.int(0, 10) - 5, random.int(0, 10) - 5)
            score += 1
        else
            snake = snake[1]

        # Print the game state
        print("Score:", score)
        print("Snake:", snake)

        # Clear the console
        clear()

        # Sleep for a short duration
        sleep(100)

# Run the game
main()
```

**Explanation:**

1. **Initialization:**
   - `snake`: A list to store the snake's coordinates.
   - `food`: A tuple to store the coordinates of the food.
   - `direction`: A string to store the current direction of the snake.
   - `length`: An integer to store the snake's length.
   - `score`: An integer to store the player's score.

2. **Game Loop:**
   - The `while true` loop runs continuously until the user quits the game.
   - `readLine()` reads the user's input.
   - The code checks for user input and updates the snake's direction accordingly.
   - `snake = snake[1]` moves the snake's head to the next position based on the current direction.
   - `if snake[0] == food[0] and snake[1] == food[1] then`: checks if the snake has eaten the food. If so, the snake's length increases, and the food is updated with new random coordinates.
   - `clear()` clears the console screen.
   - `sleep(100)` pauses the game for a short duration.

3. **Printing the Game State:**
   - The `print()` function displays the current score and the snake's position.

4. **Running the Game:**
   - `main()` starts the game loop.


**Key Points:**

- This code provides a basic framework for a console snake game.
- You can extend this code by adding features like:
    - A graphical representation of the game using `nim-gui`.
    - A timer to control the game speed.
    - Different food types or obstacles.
    - Level-based progression with increasing difficulty.
    - User-friendly interface with input validation.

- This code assumes you have Nim installed and configured.


**How to Run:**

1. Save the code as a `.nim` file (e.g., `snake.nim`).
2. Open a terminal and navigate to the directory where you saved the file.
3. Run the command `nim c snake.nim`.
4. This will compile and run the game.

Enjoy playing the Snake Game!
You  >
```
![{A5BA4616-15A0-4A88-8BA5-DD6AB9D1E67D}](https://github.com/user-attachments/assets/4a492b4a-7353-44de-ad09-3856bec45761)

**Comment by foldl** [comment]
> > Nice. Could you make a PR for this?
> 
> I'm sorry, i'm not a tech guy and English is not my native language. Due to these facts github interface isn't user-friendly for me. I don't know how to open PR.

That's fine. I will look into this.

By the way, to convert C header files to Nim, I have used [c2nim](https://github.com/Nim-lang/c2nim) a lot.

**Comment by foldl** [comment]
Here we are: 64497472624876c8f8c705f1207b54a9cecabf9d

Thanks.
