### ISSUE TITLE
chatllm_load_session example

### ISSUE THREAD

**Issue by jarroddavis68** [foldl/chatllm.cpp#43]
Do you have an example or can you show how to properly use `chatllm_load_session/chatllm_save_session`. I save the session, when I try to load it and chat, it will immediately crash
`C:\Dev\Delphi\Projects\genai\build\vendor\chatllm-cpp\ggml\src\ggml.c:1572: GGML_ASSERT(view_src == NULL || data_size == 0 || data_size + view_offs <= ggml_nbytes(view_src)) failed`

Also, when shutting down, you just quit the app? I see `chatllm_create`, how do you free the resources before your app quits?

**Comment by foldl** [comment]
This feature is lost when adding backends. Now it is reimplemented (2619cbba4902bee44408ddfab177713a77eb30f5).

A quick demo in Python:

```python
import sys, signal, os

from binding import PATH_BINDS

import chatllm
from chatllm import ChatLLM, LibChatLLM

llm: ChatLLM = None

def handler(signal_received, frame):
    if llm.is_generating:
        print('\naborting...')
        llm.abort()
    else:
        llm.show_statistics()
        sys.exit(0)

def demo_session(params, session_file_name: str, cls = ChatLLM):
    global llm
    signal.signal(signal.SIGINT, handler)
    llm = cls(LibChatLLM(PATH_BINDS), params)

    if not os.path.exists(session_file_name):
        for _i in range(2):
            s = input('You  > ')
            print('A.I. > ', end='', flush=True)
            llm.chat(s)

        print(f"saving {session_file_name}")
        llm.save_session(session_file_name)
        print(f"restart...")
        llm.restart()

    print(f"load {session_file_name}")
    llm.load_session(session_file_name)

    while True:
        s = input('You  > ')
        print('A.I. > ', end='', flush=True)
        llm.chat(s)

if __name__ == '__main__':
    demo_session(['-m', sys.argv[1]], sys.argv[2])
```

```
python demo_sess.py :qwen2.5:1.5b c:\tmp\qwen2.sess
You are served by QWen2,   
with 1543714304 (1.5B) parameters.

You  > I am James Bond. who are you?
A.I. > As an AI language model, ......
You  > I want to call you Joker.
A.I. > As an AI language model, ...
saving c:\tmp\qwen2.sess
(Ctrl + C)
```

Now run it again:

```
python demo_sess.py :qwen2.5:1.5b c:\tmp\qwen2.sess

You are served by QWen2,         
with 1543714304 (1.5B) parameters.

load c:\tmp\qwen2.sess
You  > who am I?
A.I. > You are James Bond, ...
```

**Comment by foldl** [comment]
> Also, when shutting down, you just quit the app? I see `chatllm_create`, how do you free the resources before your app quits?

Yes, just quit the app and let OS free the resources.

It is not a good practice, especially if you are using tools like Valgrind. But I would like to just keep things as simple as possible.

**Comment by jarroddavis68** [comment]
I build the latest from repo.

here is my code:
```Delphi
procedure Test01();
var
  LLlm: Pchatllm_obj;
  LInput: string;

begin
  LLlm := chatllm_create;

  chatllm_append_param(LLlm, '-m');
  chatllm_append_param(LLlm, 'C:/LLM/CHATLLM/gemma2-2b.bin');
  chatllm_append_param(LLlm, '-ngl');
  chatllm_append_param(LLlm, '99');
  chatllm_append_param(LLlm, '-t');
  chatllm_append_param(LLlm, '0');

  if chatllm_start(LLlm, chatllm_print_proc, chatllm_end_proc, LLlm) <> 0 then Exit;
  chatllm_set_gen_max_tokens(LLlm, -1);

  if TFile.Exists('session.txt') then
  begin
    if chatllm_load_session(LLlm, 'session.txt') <> 0 then Exit;
  end;

  while True do
  begin
    Write('You  > ');
    ReadLn(LInput);
    if Length(LInput) < 1 then Continue;
    Write('A.I. > ');
    if LInput = '/quit' then
      break;
    chatllm_user_input(LLlm, PUTF8Char(UTF8Encode(LInput)));

    WriteLn;
  end;

  chatllm_save_session(LLlm, 'session.txt');
end;
```
This will create a session file that HUGE in size.
![image](https://github.com/user-attachments/assets/900dcfb9-3a7e-433a-9b57-ad0bd1fa3579)

And when I load the session, it still crashes
`A.I. > C:\Dev\Delphi\Projects\Phipps\build\vendor\chatllm-cpp\ggml\src\ggml.c:1572: GGML_ASSERT(view_src == NULL || data_size == 0 || data_size + view_offs <= ggml_nbytes(view_src)) failed`

**Comment by foldl** [comment]
b48f08a65e7ec28374c69415adec7e563c0d770b fixes models using sliding window, like Gemma-2.

**Comment by jarroddavis68** [comment]
> [1b7619e](https://github.com/foldl/chatllm.cpp/commit/1b7619e15bf8f47dda8cd0edaa9c5c0b3c72fd8e) fixes models using sliding window attention, like Gemma-2.
> 
Now it works, but the session file is 650MB in size?

> By the way, `-ngl` might work, or not work. I am still working on it.

seems to be working. I enabled Vulkan, and it runs a lot faster when it's enabled.

**Comment by foldl** [comment]
> Now it works, but the session file is 650MB in size?

Yes. To keep things simple, the whole K-V cache is saved (no matter used or not).

> seems to be working. I enabled Vulkan, and it runs a lot faster when it's enabled.

This is good news. Thanks.

**Comment by jarroddavis68** [comment]
Note: qwen2.5-1.5b.bin, does not seem to work with -ngl (vulkan), it only outputs `!!!!!!!`, cpu mode it works.

**Comment by foldl** [comment]
Since session api is ok now, let's close this.
