### ISSUE TITLE
Megrez model doesn't work.

### ISSUE THREAD

**Issue by JohnClaw** [foldl/chatllm.cpp#44]
![{D81E4C38-7876-4001-A003-3110AB4428F3}](https://github.com/user-attachments/assets/63211526-4496-4a6d-9a02-c2cf346e4bf1)

**Comment by foldl** [comment]
It works fine on my machines; it's quite peculiar.

**Comment by JohnClaw** [comment]
> It works fine on my machines; it's quite peculiar.

I used convert script from your repo to make q8_0 bin file for Megrez: https://huggingface.co/NikolayKozloff/Megrez-3B-Instruct-chatllm.cpp-q8_0-q4_1-q4_0-f16-f32-GGML/resolve/main/Megrez-3B-Instruct-chatllm.cpp-GGML-q8_0.bin

**Comment by foldl** [comment]
> I also tried different approach and it raised error too:
> 
> ![{4ED6A4BA-2059-4D5D-B902-4C80B115E2D1}](https://github.com/user-attachments/assets/d2982682-5b13-4ca0-acca-3fcc583f5c9d)

`-m` is missing if you are using `main.exe` built from `main.nim`:

```sh
main -m :megrez -t 0 -i
```
which will download from https://modelscope.cn/models/judd2024/chatllm_quantized_megrez/files.

Your quantized model is different from mine:

![image](https://github.com/user-attachments/assets/b9186eca-5a3d-4094-84ab-c486a7f526bc)

**Comment by JohnClaw** [comment]
> ```shell
> main -m :megrez -t 0 -i
> ```

Got new errors:

```
c:\chlmcp>main -m :megrez -t 0 -i
oserrors.nim(92)         raiseOSError
Error: unhandled exception: Access denied.
Additional info: .\..\ [OSError]
```
