### ISSUE TITLE
Falcon 3 10b Instruct prints <|assistant|> before each answer. Can it be fixed somehow?

### ISSUE THREAD

**Issue by JohnClaw** [foldl/chatllm.cpp#46]
![{52367CF3-505E-4544-B448-3DDA500256B1}](https://github.com/user-attachments/assets/661b0b51-6aeb-428c-a9b9-7aae0d28f687)

I uploaded it to hf: https://huggingface.co/NikolayKozloff/Falcon3-10B-Instruct-chatllm.cpp-Q8_0-GGML/resolve/main/Falcon-3-10b-Instruct-chatllm.cpp-GGML-q8_0.bin?download=true

**Comment by foldl** [comment]
Interesting. I have tried several prompts, your prompt triggers "<assistant>" while others not. I think this is a "bug" in the model itself.

By the way, there is an redundant `'` character in `falcon.cpp`, which has been fixed.

**Comment by JohnClaw** [comment]
Thanks for explanation.
