### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by MarsMeng1994** [foldl/chatllm.cpp#5]
when i use cmd like: 
`./build/bin/main --model quantized.bin --prompt \"{}\"".format(prompt)`

it going to core dumped like:
`
<AI>
ggml_new_tensor_impl: not enough space in the scratch memory pool (needed 292106304, available 150994944)
Segmentation fault (core dumped)
`

how to fix?

**Comment by foldl** [comment]
Which model are you using?

________________________________
发件人: Mars ***@***.***>
发送时间: 星期一, 二月 26, 2024 2:52 下午
收件人: foldl/chatllm.cpp ***@***.***>
抄送: Subscribed ***@***.***>
主题: [foldl/chatllm.cpp] core dumped (Issue #5)


when i use cmd like:
./build/bin/main --model quantized.bin --prompt \"{}\"".format(prompt)

it going to core dumped like:
<AI> ggml_new_tensor_impl: not enough space in the scratch memory pool (needed 292106304, available 150994944) Segmentation fault (core dumped)

how to fix?

―

**Comment by foldl** [comment]
@MarsMeng1994 You can enlarge this value, such as:

https://github.com/foldl/chatllm.cpp/blob/7c212270e50431032efcd872c3d271890e425145/models/minicpm.cpp#L88

See also Issue #6.
