### ISSUE TITLE
请问如何部署BCEmbedding的rerank模型？

### ISSUE THREAD

**Issue by chenchun0629** [foldl/chatllm.cpp#7]
请问如何部署BCEmbedding的rerank模型？

**Comment by foldl** [comment]
不知道“部署”具体指的是什么。

1. 下载模型；
1. 使用 `convert.py` 转换模型；
2. 测试：

    1. 直接测试 ReRanker 模型：
   https://github.com/foldl/chatllm.cpp/blob/7df728dd47c04d795be505de11c6c5273c553f03/main.cpp#L416
   
    1. 完整的 [RAG demo](../blob/master/docs/rag.md)
