### ISSUE TITLE
LLM conversion is a issue.

### ISSUE THREAD

**Issue by netspym** [foldl/chatllm.cpp#9]
Hi I tried to convert yi-34b-chat from the full llm to .bin but facing a lot of mistakes.

Do you have a link of the yi-34b-chat.bin (a converted one) I can download and use?

Thanks
Yuming

**Comment by foldl** [comment]
Here you go:

https://www.modelscope.cn/api/v1/models/judd2024/chatllm_quantized_models/repo?Revision=master&FilePath=yi-34b-q4.bin

**Comment by netspym** [comment]
Thanks a lot!
